[continuous-deploy-fingerprint] Add platform as input
expo/expo-github-action pull request #280
Opened 2024-04-26 18:38 UTC by NoZiL

Playing with the new action for sdk 51, I've noticed that the platform is missing.
This is an attempt to handle this case.

2024-08-29 00:36 UTC, brentvatne approved these changes
can you update the readme as well?

2024-09-03 19:34 UTC, wschurman requested changes
Good addition! Just a few stylistic changes, then I'll merge!

2024-09-03 19:34 UTC, wschurman commented on src/actions/continuous-deploy-fingerprint.ts
> +  async function buildAndroid() {
```suggestion
  async function buildAndroidIfNecessaryAsync() {
```

2024-09-03 19:34 UTC, wschurman commented on src/actions/continuous-deploy-fingerprint.ts
> +    if (platform === 'ios') return;
small nit (null is clearer in result type than void):
```suggestion
    if (platform === 'ios') {
      return null;
    }
```

2024-09-03 19:34 UTC, wschurman commented on src/actions/continuous-deploy-fingerprint.ts
> +  async function buildIos() {
```suggestion
  async function buildIosIfNecessaryAsync() {
```

2024-09-03 19:34 UTC, wschurman commented on src/actions/continuous-deploy-fingerprint.ts
> +    if (platform === 'android') return;
```suggestion
    if (platform === 'android') {
      return null;
    }
```

2024-09-03 19:34 UTC, wschurman commented on src/actions/continuous-deploy-fingerprint.ts
> +  const [android, ios] = await Promise.all([buildAndroid(), buildIos()]);
```suggestion
  const [androidResult, iosResult] = await Promise.all([
    buildAndroidIfNecessaryAsync(), 
    buildIosIfNecessaryAsync(),
  ]);
```

2024-09-03 19:34 UTC, wschurman commented on src/actions/continuous-deploy-fingerprint.ts
> +      builds: [android?.buildInfo, ios?.buildInfo].filter(e => e !== undefined) as BuildInfo[],
```suggestion
      builds: [android?.buildInfo, ios?.buildInfo].filter(e => e !== null) as BuildInfo[],
```

2024-09-24 17:07 UTC, NoZiL commented
Hey @brentvatne, I added the input in the readme, tell me if something else needs to be added.
Hey @wschurman, sorry for the delay, I've dealt with the conflicts and added your suggestions. I also added the strict null checks in tsconfig to lint accordingly.

2024-09-24 19:47 UTC, wschurman approved these changes

2024-09-24 19:48 UTC, merged

2024-09-24 19:48 UTC, wschurman commented
Thanks for the contribution!